[package]
name = "offerings-scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
dialoguer = "0.11.0"
reqwest = { version = "0.12.12", features = ["blocking", "json", "rustls-tls"] }
scraper = "0.22.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
